pages:
    - Home: 'index.md'
    - Getting Started: 'started.md'
    - Base Actions:
      - dict: 'actions/dict.md'
      - lang: 'actions/lang.md'
      - loot: 'actions/loot.md'
      - recipes: 'actions/recipes.md'
    - Mod Actions:
      - Immersive Engineering:
        - ie: 'actions/ie/ie.md'
        - ie.alloy: 'actions/ie/ie_alloy.md'
        - ie.blastfurnace: 'actions/ie/ie_blastfurnace.md'
        - ie.cokeoven: 'actions/ie/ie_cokeoven.md'
        - ie.crusher: 'actions/ie/ie_crusher.md'
      - Just Enough Items:
        - jei: 'actions/jei/jei.md'
    - Arguments:
      - all: 'arguments/all.md'
      - boolean: 'arguments/boolean.md'
      - dict: 'arguments/dict.md'
      - float: 'arguments/float.md'
      - ingredient: 'arguments/ingredient.md'
      - integer: 'arguments/integer.md'
      - null: 'arguments/null.md'
      - recipeShaped: 'arguments/recipeshaped.md'
      - recipeShapeless: 'arguments/recipeshapeless.md'
      - stack: 'arguments/stack.md'
      - stackList: 'arguments/stacklist.md'
      - string: 'arguments/string.md'
      - stringList: 'arguments/stringlist.md'
    - Commands:
      - dict: 'commands/dict.md'
      - hand: 'commands/hand.md'
      - loot: 'commands/loot.md'
      - recipes: 'commands/recipes.md'
    - Glossary:
      - Enchantments: 'glossary/enchantments.md'
      - Loot Tables: 'glossary/loottables.md'
      - IE - Multiblocks: 'glossary/multiblocks.md'
        
theme: 
    name: null
    custom_dir: tweaked_theme

site_name: Tweaked Documentation
site_url: 'https://mabinogigaming.github.io/Tweaked/'
site_author: Mabinogi

markdown_extensions:
    - admonition
    - smarty
    - sane_lists
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: false
    - toc:
        permalink: ' '

extra:
  logo: 'img/favicon.ico'
  history_buttons: false
  article_nav_top: false
  version: '0.3.1'